name: test-docker

on:
  workflow_dispatch:
  push:
    branches:
      - forgejo

jobs:
  test:
    runs-on: docker
    steps:
      - name: Test echo
        run: |
          echo "Hello from docker runner!"
          echo "Runner should be working"
          uname -a
          cat /etc/os-release
