apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- automation/n8n-pg.yaml
- automation/n8n.yaml
- infrastructure/cloudflared.yaml
- infrastructure/homepage-app.yaml
- infrastructure/homepage-config.yaml
- infrastructure/homepage-rbac.yaml
- infrastructure/kaniko-relay.yaml
- infrastructure/longhorn-monitor.yaml
- infrastructure/longhorn.yaml
- infrastructure/monitoring.yaml
- infrastructure/pgweb.yaml
- infrastructure/relay.yaml
- infrastructure/reloader.yaml
- infrastructure/renovate.yaml
- infrastructure/vaultwarden.yaml
- media/jackett.yaml
- media/torrenter.yaml
- productivity/forgejo.yaml
- productivity/obsidian-sync.yaml
- productivity/the-grid.yaml
