apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:iwmd,iv:aVrBPUDJi9mE+Gc3fmTVZj7sVS9JvKyO4BS5EYpZKZI=,tag:b3Gyy8h40hXrTIcZe/jqrg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Im+oQ6HosdgcrNMggW2tYyjecoQO4Q==,iv:lo/Zd4tpT757PpSx5pgVwYP0vZBhfVFSt+Fk7TulIXA=,tag:O6grFc28HPEpeg8FVXBTpQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:8XHg,iv:nzNXfpIKpdD9FnYnr6dDonWTPs8C3NgUQKh3G63E6xg=,tag:67V2V345qqNO6C0hCYTidQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaytudHF4M1VsN1NKNDNp
            ZDJRa09KS1BpOWd5dWJiQ200NG5QSUtiZm5zCklVUW9tOU1nb0FJZGpoVDRHMlVw
            aXZlRkgwbElsU2lSdTNockJyM0NJQ28KLS0tIGk2RHpGVjIrcnQ3V0lSelJhcjIy
            ZTVwdFBYbWhiaWJqTXV0UWIxeHRqMkkKlMBa1Ci2VcVKJe5MC6uQeDT5SBE8kXue
            QjSyJOl+iQQqFS8w8xWN3DmGHaaMeFC3GQjw/o0yyBJtzlzOT9XLnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:55:29Z"
    mac: ENC[AES256_GCM,data:Bn+mYH8WdVn67hf2dGxKxFtj6Ixs/VcQHvgkXUrr6VnqTbl7FSOUipM7lnx2m551Kj7XGGw8D8fcGf/NBGQNj4ongZG4BIjYGMqTYFZ8b95bwJM94v6ydVHMI7w/BNgB4a3r9C8SDe0eKPGq+VcR+o+/4VeqyXFeOedOWGw9RCc=,iv:W8km1aMJCWXXWTUlJLdUckB/ZwDwkaAlfQL/4B4Fq3k=,tag:BFz1WKPlqKRhripcDzD+cw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:+8g1ndbKUhLMC4gD+QpquUy5MQ5ZD3kd0/V5olyTu3E=,iv:S+yt7tXwPeENGALFV7s9d32+DKjjM/2SISpdRapEUO8=,tag:Ly8AjP7rqvWFfKDzTQZ7kg==,type:str]
    N8N_URL: ENC[AES256_GCM,data:finPOSAqqYxo3arQov9JVvVq3Xyai4pcV+FIUw==,iv:vgXGYF+Qs7SzGvj3Z6RIuQ/vL8h+hP86+AZs1cWjfC4=,tag:IhH9Ep8UaB/+/mib4CZb2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaytudHF4M1VsN1NKNDNp
            ZDJRa09KS1BpOWd5dWJiQ200NG5QSUtiZm5zCklVUW9tOU1nb0FJZGpoVDRHMlVw
            aXZlRkgwbElsU2lSdTNockJyM0NJQ28KLS0tIGk2RHpGVjIrcnQ3V0lSelJhcjIy
            ZTVwdFBYbWhiaWJqTXV0UWIxeHRqMkkKlMBa1Ci2VcVKJe5MC6uQeDT5SBE8kXue
            QjSyJOl+iQQqFS8w8xWN3DmGHaaMeFC3GQjw/o0yyBJtzlzOT9XLnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:55:29Z"
    mac: ENC[AES256_GCM,data:Bn+mYH8WdVn67hf2dGxKxFtj6Ixs/VcQHvgkXUrr6VnqTbl7FSOUipM7lnx2m551Kj7XGGw8D8fcGf/NBGQNj4ongZG4BIjYGMqTYFZ8b95bwJM94v6ydVHMI7w/BNgB4a3r9C8SDe0eKPGq+VcR+o+/4VeqyXFeOedOWGw9RCc=,iv:W8km1aMJCWXXWTUlJLdUckB/ZwDwkaAlfQL/4B4Fq3k=,tag:BFz1WKPlqKRhripcDzD+cw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:fJeqNYT8yRCywYaxeZk1OVhEMb1kTLqITUEc34A3P7t3/fJ8fttHpGUXyZC3/Y8bY2MGRdc5WMTRxutIUsI4x2R8YHsHiL0GpoGR8z+lukp/OoIR9CNAFedFkJ6Jpt3d5yuqgAlnDZqV9kc7rn8pcbfI+C35cIJ5vQeIEgL/ifk5lu3ulLe2gTbHkw5f92wwfohZByu2DHI7gaf4QlDWYwNTgjSBh9vOPajxbK69U2iaw6teg9fpYw==,iv:x8sJNe51W8jXJn/L31OkqloETwi6d8Vr0myEbLG1krA=,tag:gnBzXRqR+/7Ah2sg3JdhXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaytudHF4M1VsN1NKNDNp
            ZDJRa09KS1BpOWd5dWJiQ200NG5QSUtiZm5zCklVUW9tOU1nb0FJZGpoVDRHMlVw
            aXZlRkgwbElsU2lSdTNockJyM0NJQ28KLS0tIGk2RHpGVjIrcnQ3V0lSelJhcjIy
            ZTVwdFBYbWhiaWJqTXV0UWIxeHRqMkkKlMBa1Ci2VcVKJe5MC6uQeDT5SBE8kXue
            QjSyJOl+iQQqFS8w8xWN3DmGHaaMeFC3GQjw/o0yyBJtzlzOT9XLnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:55:29Z"
    mac: ENC[AES256_GCM,data:Bn+mYH8WdVn67hf2dGxKxFtj6Ixs/VcQHvgkXUrr6VnqTbl7FSOUipM7lnx2m551Kj7XGGw8D8fcGf/NBGQNj4ongZG4BIjYGMqTYFZ8b95bwJM94v6ydVHMI7w/BNgB4a3r9C8SDe0eKPGq+VcR+o+/4VeqyXFeOedOWGw9RCc=,iv:W8km1aMJCWXXWTUlJLdUckB/ZwDwkaAlfQL/4B4Fq3k=,tag:BFz1WKPlqKRhripcDzD+cw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    VW_URL: ENC[AES256_GCM,data:bBe1nS/P/es4NY99OilDc8D8h2HvV+XjmQAI5Z5ixHXjlw==,iv:asmsWebLUhsevt1/PgLU4BIDHGDR1obhtL+EM8XvvxQ=,tag:icK5NHItpdiKRvspmt+hGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaytudHF4M1VsN1NKNDNp
            ZDJRa09KS1BpOWd5dWJiQ200NG5QSUtiZm5zCklVUW9tOU1nb0FJZGpoVDRHMlVw
            aXZlRkgwbElsU2lSdTNockJyM0NJQ28KLS0tIGk2RHpGVjIrcnQ3V0lSelJhcjIy
            ZTVwdFBYbWhiaWJqTXV0UWIxeHRqMkkKlMBa1Ci2VcVKJe5MC6uQeDT5SBE8kXue
            QjSyJOl+iQQqFS8w8xWN3DmGHaaMeFC3GQjw/o0yyBJtzlzOT9XLnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:55:29Z"
    mac: ENC[AES256_GCM,data:Bn+mYH8WdVn67hf2dGxKxFtj6Ixs/VcQHvgkXUrr6VnqTbl7FSOUipM7lnx2m551Kj7XGGw8D8fcGf/NBGQNj4ongZG4BIjYGMqTYFZ8b95bwJM94v6ydVHMI7w/BNgB4a3r9C8SDe0eKPGq+VcR+o+/4VeqyXFeOedOWGw9RCc=,iv:W8km1aMJCWXXWTUlJLdUckB/ZwDwkaAlfQL/4B4Fq3k=,tag:BFz1WKPlqKRhripcDzD+cw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: torrenter-secrets
    namespace: default
type: Opaque
stringData:
    JACKETT_URL: ENC[AES256_GCM,data:vwymAiiqL9bNSNSgmtGS6HgLYh6rUbheOdw9,iv:Ngo5HmPe9UsZjCB/Qdb5gOy/NczZPWPK3yYqR+g3Nx0=,tag:mJnVW3SlXMn0hopjS3Xjug==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:p1QKKqu5LbBvbn5Vim9gzxF32LEA7YbdSpynzGwPGmE=,iv:xVfs2L8rJk1rGkZpaPiMim/IMJhwZzfzKUM9gkdAct8=,tag:i7ARNpNapaKJOJSVdH3ZBQ==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:d64UQJINlzIupg6b/7Wsqcm7JFHwbWiwAS8nyd8PcbY=,iv:JdIaiLjT380mouPXib1r2uXp6qgcwuI9cE5WfvLwAUU=,tag:UyJpjQBt7aStQ0kQNMOlRg==,type:str]
    TMDB_READ_TOKEN: ENC[AES256_GCM,data:Hcx0M16MBxpa+7hLGikVyEqD7zXw/csDPd2ZSlW4GXsHfhQIQGZ8dz2tjonYtuoWknj0Fc+8SwVnmN295sFyesdku/1BJBoe2Zvyixi/1fD55zvxKvswBKOQNqdsu+c659F7v4MpNAcirycfCPi27W/5LnNAZRjfZJQC6Ymqvm0oGcfCqudfWz5L7MWVcOmrATVvI6az2Re86RYMiC/bhG5VMtQAnLVKly34X7D3yBwVFPTYDz0uaJcbJSOUdT8U7gDpgAu9HU8Ule6aQDVRfl2KwVYvgPjbNmwuvAUweRhmjhVDGM6ND3gFHHc5,iv:eQLY80ap86r0eg+EKtihCC9rxBi2z6O5RsPd01SN+Z4=,tag:/dhYox662KYT7qKLLbjunw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaytudHF4M1VsN1NKNDNp
            ZDJRa09KS1BpOWd5dWJiQ200NG5QSUtiZm5zCklVUW9tOU1nb0FJZGpoVDRHMlVw
            aXZlRkgwbElsU2lSdTNockJyM0NJQ28KLS0tIGk2RHpGVjIrcnQ3V0lSelJhcjIy
            ZTVwdFBYbWhiaWJqTXV0UWIxeHRqMkkKlMBa1Ci2VcVKJe5MC6uQeDT5SBE8kXue
            QjSyJOl+iQQqFS8w8xWN3DmGHaaMeFC3GQjw/o0yyBJtzlzOT9XLnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:55:29Z"
    mac: ENC[AES256_GCM,data:Bn+mYH8WdVn67hf2dGxKxFtj6Ixs/VcQHvgkXUrr6VnqTbl7FSOUipM7lnx2m551Kj7XGGw8D8fcGf/NBGQNj4ongZG4BIjYGMqTYFZ8b95bwJM94v6ydVHMI7w/BNgB4a3r9C8SDe0eKPGq+VcR+o+/4VeqyXFeOedOWGw9RCc=,iv:W8km1aMJCWXXWTUlJLdUckB/ZwDwkaAlfQL/4B4Fq3k=,tag:BFz1WKPlqKRhripcDzD+cw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-secrets
    namespace: default
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:kyxBJCZP/w==,iv:KvKHS2G3aSU6Fhq6ujSJZ499I2AvoHQoASRc/TiLjqU=,tag:Ko+b834/uLBENY1JrNM47Q==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:SsaUJ9yFNWesna5YYBsNDEphkY0=,iv:nHB/1ti1keG/2H9pTeX87CUF9YlvxfB9HnxF2tmk61k=,tag:oXTn7vIt9mhkT+1QVWD/aA==,type:str]
    COUCHDB_URL: ENC[AES256_GCM,data:5iql8t40ZFaKbmXNzCCGPN5eLLiWZyOX1TaxdbRMFPqpjAH8Tg==,iv:A1ORqDj0jTjFfsNyiPyeZQRjsKogICWqAwNE7v06ldE=,tag:zr5ivXAvHW0cpn32pR0bxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaytudHF4M1VsN1NKNDNp
            ZDJRa09KS1BpOWd5dWJiQ200NG5QSUtiZm5zCklVUW9tOU1nb0FJZGpoVDRHMlVw
            aXZlRkgwbElsU2lSdTNockJyM0NJQ28KLS0tIGk2RHpGVjIrcnQ3V0lSelJhcjIy
            ZTVwdFBYbWhiaWJqTXV0UWIxeHRqMkkKlMBa1Ci2VcVKJe5MC6uQeDT5SBE8kXue
            QjSyJOl+iQQqFS8w8xWN3DmGHaaMeFC3GQjw/o0yyBJtzlzOT9XLnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:55:29Z"
    mac: ENC[AES256_GCM,data:Bn+mYH8WdVn67hf2dGxKxFtj6Ixs/VcQHvgkXUrr6VnqTbl7FSOUipM7lnx2m551Kj7XGGw8D8fcGf/NBGQNj4ongZG4BIjYGMqTYFZ8b95bwJM94v6ydVHMI7w/BNgB4a3r9C8SDe0eKPGq+VcR+o+/4VeqyXFeOedOWGw9RCc=,iv:W8km1aMJCWXXWTUlJLdUckB/ZwDwkaAlfQL/4B4Fq3k=,tag:BFz1WKPlqKRhripcDzD+cw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: freescout-secrets
    namespace: default
type: Opaque
stringData:
    FREESCOUT_DB_ROOT_PASSWORD: ENC[AES256_GCM,data:3B8h50P0zz+Z8xbmLP7WdUkjlRo=,iv:P4OvUt5W7EmPhRLd6lrFtBpGecuC5MXMsoNKutOJ/J4=,tag:0dMrOkOHpUDv4t+zh5bgDg==,type:str]
    FREESCOUT_DB_PASSWORD: ENC[AES256_GCM,data:XuJPuSwMDqLGZrmJ22OusPoZqU8=,iv:YVIAn4Vs5OMpvowsG7OgRxGl+q1MNbck55sjdQjHnxY=,tag:Cr3FI/O0q0/aLqZPA8iK+Q==,type:str]
    FREESCOUT_ADMIN_EMAIL: ENC[AES256_GCM,data:6oGeH9sanrrZxlxYDcgdcmFN6lIqvlQ=,iv:g7hNRARu3nrGgGYm1i5o9rhtlnsamElFRcwdzC++Syg=,tag:QGCNKZUkypeOQG3aJHG1tg==,type:str]
    FREESCOUT_ADMIN_PASSWORD: ENC[AES256_GCM,data:JK+NgIwCed+xPnKYnsgrUt0QpTk=,iv:ygSDAV3gWs7VE6PwumZRiVhKHwNfUBwIjRTWuAsn4bk=,tag:sNw2gxx3d0KXZn89TYvnQA==,type:str]
    FREESCOUT_SITE_URL: ENC[AES256_GCM,data:yhQbDIhgOjk7RsreLslwOU6ad0mgd4/fXolwRQ==,iv:T8oTPObz3EioWseUrKM5ZVy8bKNz4+tYjCUAtplebUY=,tag:CJOAM7drW6GQFZ+QtJF4Iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaytudHF4M1VsN1NKNDNp
            ZDJRa09KS1BpOWd5dWJiQ200NG5QSUtiZm5zCklVUW9tOU1nb0FJZGpoVDRHMlVw
            aXZlRkgwbElsU2lSdTNockJyM0NJQ28KLS0tIGk2RHpGVjIrcnQ3V0lSelJhcjIy
            ZTVwdFBYbWhiaWJqTXV0UWIxeHRqMkkKlMBa1Ci2VcVKJe5MC6uQeDT5SBE8kXue
            QjSyJOl+iQQqFS8w8xWN3DmGHaaMeFC3GQjw/o0yyBJtzlzOT9XLnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:55:29Z"
    mac: ENC[AES256_GCM,data:Bn+mYH8WdVn67hf2dGxKxFtj6Ixs/VcQHvgkXUrr6VnqTbl7FSOUipM7lnx2m551Kj7XGGw8D8fcGf/NBGQNj4ongZG4BIjYGMqTYFZ8b95bwJM94v6ydVHMI7w/BNgB4a3r9C8SDe0eKPGq+VcR+o+/4VeqyXFeOedOWGw9RCc=,iv:W8km1aMJCWXXWTUlJLdUckB/ZwDwkaAlfQL/4B4Fq3k=,tag:BFz1WKPlqKRhripcDzD+cw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    namespace: default
type: Opaque
stringData:
    FORGEJO_DB_PASSWORD: ENC[AES256_GCM,data:j6Bh89QXU/s9SJyINZQZcaJYnK31OlHFp0e8Ok1+ZQLHy2K5ofhVdgVW78E=,iv:HqpIHWFvvkyP5SgeDfHPTT1D9N7NbQAM9XCJoJC5sRU=,tag:GLXrO6JemSJFU0yl64SScw==,type:str]
    FORGEJO_URL: ENC[AES256_GCM,data:vKaiPv32v9AqspohnUOr6Lp6Hc6AjNAdgcUk,iv:eepXEknF9CA5SNzpDOPyqCRf/cFhEfObABmYsK1KlAg=,tag:VJR9wv1OnsWAFTJw9M/ciQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qf4h0dz5mjzx75vj4dl9ak6uvuq8ucujhsnc52scdrxp400lu4jqajyxmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaytudHF4M1VsN1NKNDNp
            ZDJRa09KS1BpOWd5dWJiQ200NG5QSUtiZm5zCklVUW9tOU1nb0FJZGpoVDRHMlVw
            aXZlRkgwbElsU2lSdTNockJyM0NJQ28KLS0tIGk2RHpGVjIrcnQ3V0lSelJhcjIy
            ZTVwdFBYbWhiaWJqTXV0UWIxeHRqMkkKlMBa1Ci2VcVKJe5MC6uQeDT5SBE8kXue
            QjSyJOl+iQQqFS8w8xWN3DmGHaaMeFC3GQjw/o0yyBJtzlzOT9XLnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:55:29Z"
    mac: ENC[AES256_GCM,data:Bn+mYH8WdVn67hf2dGxKxFtj6Ixs/VcQHvgkXUrr6VnqTbl7FSOUipM7lnx2m551Kj7XGGw8D8fcGf/NBGQNj4ongZG4BIjYGMqTYFZ8b95bwJM94v6ydVHMI7w/BNgB4a3r9C8SDe0eKPGq+VcR+o+/4VeqyXFeOedOWGw9RCc=,iv:W8km1aMJCWXXWTUlJLdUckB/ZwDwkaAlfQL/4B4Fq3k=,tag:BFz1WKPlqKRhripcDzD+cw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
